development:
  s3_bucket: "soundtom-dev"

production:
  s3_bucket: "soundtom-pro"

s3_region:  "us-east-1"
s3_access_key_id: "AKIAIGRYE24MYXEWEWVA"
s3_secret_access_key: "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"
